package exercicio3

import java.lang.ArithmeticException

class CalculoMatematico {
    fun divisao(numero1: Int, numero2: Int) throw ArithmeticException : Int{
            return numero1 / numero2
    }
}